
name: Flutter Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "assets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0" # adjust if needed
          channel: "stable"
          cache: true

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pharmasoft-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
