
name: pharmasoft_pro
description: Pharmacy accounting & admin app (multi-tenant; per-pharmacy branding).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  flutter_barcode_scanner: ^2.0.0
  pdf: ^3.11.0
  printing: ^5.12.0
  excel: ^4.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/
